# Generated by Django 3.2 on 2021-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
