# Generated by Django 3.2 on 2021-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_addpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
