# Generated by Django 3.2 on 2021-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_addpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
