# Generated by Django 3.2 on 2021-09-30 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_addpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
