# Generated by Django 3.2 on 2021-10-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_addpost_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={'verbose_name': 'Dog'},
        ),
        migrations.AlterModelTable(
            name='addpost',
            table='music_album',
        ),
    ]
