# Generated by Django 3.2 on 2021-10-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211006_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={},
        ),
        migrations.AlterModelTable(
            name='addpost',
            table=None,
        ),
    ]
