# Generated by Django 3.2 on 2021-10-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211006_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={'get_latest_by': 'date'},
        ),
    ]
