# Generated by Django 3.2 on 2021-10-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_addpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={'get_latest_by': 'date'},
        ),
    ]
