# Generated by Django 3.2 on 2021-10-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_addpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={},
        ),
    ]
