# Generated by Django 3.2.9 on 2021-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_addpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='content',
            field=models.TextField(),
        ),
    ]
