# Generated by Django 4.0.1 on 2022-02-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_addpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpost',
            options={'get_latest_by': 'postId'},
        ),
    ]
